### ISSUE TITLE
Not receiving any transferred bytes

### ISSUE THREAD

**Issue by Makkmetp** [piwik/plugin-Bandwidth#30]
Hi, 
I have recently installed the bandwith plugin on two Matomo installation, but not one of them is receiving any transferred bytes. Even when multiple PDF-documents are downloaded and pages are viewed. 
The tracking code is placed with the tagmanager.
Matomo: 3.14
Websever: Nginx
PHP: 7.2.11

Do I miss some settings?

**Comment by tsteur** [comment]
@Makkmetp thanks for creating this issue. The plugin requires the use of [Log Analytics](https://matomo.org/log-analytics/) see https://plugins.matomo.org/Bandwidth#faq unless you do some custom tracking implementation unfortunately. This might explain the issue?

**Comment by Makkmetp** [comment]
@tsteur Thank you for the explanation. To bad. 
Do you know if it is possible to measure this with the standard tag of Matomo without using custom dimensions? 
I am very interested in this information.

**Comment by tsteur** [comment]
You would need to call `_paq.push(['appendToTrackingUrl', '&bw_bytes=1234']);` where `1234` is replaced with the actual number of bytes. You would need to call this method before a tracking request and should reset it after the tracking request like `_paq.push(['appendToTrackingUrl', '']);`. It's possible to do it but it's not trivial very likely. Especially since it means you might need to manually track specific downloads for example.

For more questions/details about this I recommend you ask in our forum https://forum.matomo.org/
