### ISSUE TITLE
Graph Unit on  "Visitors => Overview" 

### ISSUE THREAD

**Issue by tonydef-seryce** [piwik/plugin-Bandwidth#49]
Hello,

It seems there is an issue with the graph unit displayed on Visitors / Overview. It'snot making the difference between M Bytes and G Bytes.

Env: Ubuntu 22.10 / Matomo 4.10.1 / Bandwidth 4.0.2
Note: I tried on our current Matomo website and in a empty Matomo database just in case and I had the same issue.

As you can see on this screen , for the  14 July, we had 374.36 M Bytes and for 15 July, we had 3.54 G Bytes.
The plugin seems not making any difference between M and G as you can see on the graph, the value of the 14 July (374.36 M) is set higher than the value of the 15 July ( 3.54 G Bytes)

![ApplicationFrameHost_pX0JoeMQN4](https://user-images.githubusercontent.com/57333465/180173585-f6bcfecf-b4aa-4481-b6b2-a0805920a152.png)

**Comment by sgiehl** [comment]
Hi @tonydef-seryce 
Thanks for creating this issue. This bug should have already been addressed in https://github.com/matomo-org/plugin-Bandwidth/pull/46
But this requires a change in core in order to work (See https://github.com/matomo-org/matomo/pull/19057)
It should be fixed with the next release of Matomo.

**Comment by tonydef-seryce** [comment]
oh sorry, thanks a lot for your quick answer!
